[build]
  command = "npm run build"
  publish = ".next"
  edge_functions = ".netlify/edge-functions"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_EMAILJS_SERVICE_ID,NEXT_PUBLIC_EMAILJS_TEMPLATE_ID,NEXT_PUBLIC_EMAILJS_PUBLIC_KEY,NEXT_PUBLIC_TURNSTILE_SITE_KEY"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "npm run dev"
  port = 3000

