export function PrivacyPolicy() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-8">
      <div className="space-y-4">
        <h1 className="text-4xl md:text-5xl font-bold text-foreground">Privacy Policy</h1>
        <p className="text-muted-foreground text-lg">
          Last updated: {new Date().toLocaleDateString('en-GB', { year: 'numeric', month: 'long', day: 'numeric' })}
        </p>
      </div>

      <div className="prose prose-lg max-w-none space-y-8 text-foreground">
        <section className="space-y-4">
          <p className="text-muted-foreground leading-relaxed">
            This Privacy Policy details TPM HIVE's approach to Data Protection and Privacy to fulfil its obligations under the applicable laws and regulations. This Privacy Policy applies to your Personal Data which is processed by us, in order to better your experience and improve the service.
          </p>
          <p className="text-muted-foreground leading-relaxed">
            In this Privacy Policy, the expressions 'Personal Data', 'Data Subject', 'Controller' and 'Processor' shall have the meanings given to them in the applicable privacy laws.
          </p>
          <p className="text-muted-foreground leading-relaxed">
            Throughout this privacy policy, the terms viz. ("we", "us", "our", "ours") refer to TPM HIVE (THEPEPPERMINT LTD). Wherever it's mentioned "you" or "your", this means YOU (as a Data Subject).
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-3xl font-bold text-foreground pt-8 border-t border-border">DEFINITIONS</h2>
          
          <div className="space-y-3">
            <div>
              <h3 className="text-xl font-semibold text-foreground mb-2">Service</h3>
              <p className="text-muted-foreground">Service is referred to as the website operated by TPM HIVE (THEPEPPERMINT LTD).</p>
            </div>
            
            <div>
              <h3 className="text-xl font-semibold text-foreground mb-2">Personal Data</h3>
              <p className="text-muted-foreground">Personal Data means any information relating to an identified individual who can be identified from those data directly or indirectly.</p>
            </div>
            
            <div>
              <h3 className="text-xl font-semibold text-foreground mb-2">Usage Data</h3>
              <p className="text-muted-foreground">Usage Data is any data collected by the Service Provider relating to the usage of the Website, traffic logs, user conduct or the results of using any Software offered as part of the Services.</p>
            </div>
            
            <div>
              <h3 className="text-xl font-semibold text-foreground mb-2">Cookies</h3>
              <p className="text-muted-foreground">Cookies are a small amount of data generated by the website and stored on your web browser (Computer or mobile device).</p>
            </div>
            
            <div>
              <h3 className="text-xl font-semibold text-foreground mb-2">Data Controller</h3>
              <p className="text-muted-foreground">Data Controller means a legal person who (either alone or in a group with others) determines the purposes for any personal information to be processed.</p>
              <p className="text-muted-foreground mt-2">In regard to this Privacy Policy, we are a Data Controller of your Personal Data.</p>
            </div>
            
            <div>
              <h3 className="text-xl font-semibold text-foreground mb-2">Data Processor</h3>
              <p className="text-muted-foreground">Data Processor, also known as Service Provider means a legal person who processes the data on behalf of the Data Controller.</p>
              <p className="text-muted-foreground mt-2">In simple terms, "We play the role of a Data Controller when we collect and process Personal Data about you and we play the role of a Data Processor when we collect and process Personal Data on behalf of another Data Controller".</p>
            </div>
            
            <div>
              <h3 className="text-xl font-semibold text-foreground mb-2">Data Subject (User)</h3>
              <p className="text-muted-foreground">Data Subject is any living individual who is using our Service and is the subject of Personal Data.</p>
            </div>
          </div>
        </section>

        <section className="space-y-4">
          <h2 className="text-3xl font-bold text-foreground pt-8 border-t border-border">PERSONAL DATA</h2>
          <p className="text-muted-foreground leading-relaxed">
            We are permitted to process your Personal Data in compliance with applicable rules and regulations by relying on one or more of the following lawful bases:
          </p>
          <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-4">
            <li>You have explicitly agreed to us processing your Personal Data for a specific reason.</li>
            <li>The processing is necessary to perform the agreement we have with you or to take steps to enter into an agreement with you.</li>
            <li>The processing is necessary to be in compliance with our legal obligations.</li>
            <li>The processing is necessary for the purposes of a legitimate interest ("Legitimate Interest") pursued by us, such as:
              <ul className="list-disc list-inside ml-6 mt-2 space-y-1">
                <li>To provide services to you,</li>
                <li>to evaluate, develop or improve our products and services</li>
              </ul>
            </li>
          </ul>
          <p className="text-muted-foreground leading-relaxed font-semibold mt-4">
            Categories of Personal Data collected and processed by us are as follows:
          </p>
        </section>

        <section className="space-y-4">
          <h3 className="text-2xl font-semibold text-foreground pt-6">DEMOGRAPHIC AND IDENTITY DATA:</h3>
          <div className="space-y-2 text-muted-foreground">
            <p><strong className="text-foreground">Contact details:</strong></p>
            <ul className="list-disc list-inside space-y-1 ml-4">
              <li>First name and Last name</li>
              <li>Email address</li>
              <li>Contact number</li>
              <li>Shipping address</li>
              <li>Country</li>
              <li>Details such as Transaction amount, Bank Name, Card Type, Card number etc.</li>
            </ul>
          </div>
        </section>

        <section className="space-y-4">
          <h3 className="text-2xl font-semibold text-foreground pt-6">LOCATION AND USAGE DATA:</h3>
          <div className="space-y-3 text-muted-foreground">
            <div>
              <p><strong className="text-foreground">Online Identifiers and other Technical Data:</strong></p>
              <ul className="list-disc list-inside space-y-1 ml-4 mt-2">
                <li>Location details such as data we get about your location, IP address, logs, or from where you connect a computer to the internet.</li>
                <li>Technical details such as device information, location and network carrier when you use our service in your mobile device.</li>
                <li>Communications details such as the Personal Data we get from communications done through e-mails, SMS, instant messages and calls are kept in record.</li>
                <li>Usage data details such as data about how you use our website (Page visit duration) or web-based properties, pages viewed, etc.</li>
              </ul>
            </div>
          </div>
        </section>

        <section className="space-y-4">
          <h2 className="text-3xl font-bold text-foreground pt-8 border-t border-border">COOKIES & TRACKING DATA</h2>
          <p className="text-muted-foreground leading-relaxed">
            Cookies are small text files that are placed on your computer by websites that you visit. Similarly, there are other types of trackers used. These are used to make websites work more efficiently, as well as to provide information to the owners of the website or service.
          </p>
          <p className="text-muted-foreground leading-relaxed">
            We use cookies, permissions and other trackers in our website, web-based properties that are used to collect and process data about you so we can provide you with a better online experience as well as improve our services.
          </p>
          <p className="text-muted-foreground leading-relaxed">
            Below are the categories of cookies used on our website along with a description of what they are used for:
          </p>

          <div className="space-y-4 mt-6">
            <div className="bg-card border border-border rounded-lg p-6">
              <h3 className="text-xl font-semibold text-foreground mb-3">Strictly Necessary</h3>
              <p className="text-muted-foreground leading-relaxed">
                These cookies are needed to run our website, to keep it secure if you are logged on and to obey regulations that apply to us.
              </p>
              <p className="text-muted-foreground leading-relaxed mt-2">
                If you are a customer, they help us know who you are so that you can log on and manage your accounts. They also help us keep your details safe and private.
              </p>
            </div>

            <div className="bg-card border border-border rounded-lg p-6">
              <h3 className="text-xl font-semibold text-foreground mb-3">Functional</h3>
              <p className="text-muted-foreground leading-relaxed">
                These cookies are used for remembering things like:
              </p>
              <ul className="list-disc list-inside space-y-1 text-muted-foreground ml-4 mt-2">
                <li>Your user ID on the log on page</li>
                <li>Your region or country</li>
                <li>Your preferred language</li>
                <li>Accessibility options like large font or high contrast pages</li>
              </ul>
            </div>

            <div className="bg-card border border-border rounded-lg p-6">
              <h3 className="text-xl font-semibold text-foreground mb-3">Performance</h3>
              <p className="text-muted-foreground leading-relaxed">
                These cookies tell us how you and our other customers use our website. We combine all this data together and study it. This helps us to:
              </p>
              <ul className="list-disc list-inside space-y-1 text-muted-foreground ml-4 mt-2">
                <li>Improve the performance of our services</li>
                <li>Improve the products we provide</li>
              </ul>
            </div>
          </div>

          <p className="text-muted-foreground leading-relaxed mt-4">
            Most web browsers allow some control of most cookies through the browser settings. Please note disabling the 'Strictly Necessary' cookies may cause certain parts of our website to remain inaccessible to you.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-3xl font-bold text-foreground pt-8 border-t border-border">USE OF DATA</h2>
          <p className="text-muted-foreground leading-relaxed">
            We are committed to treating data privacy seriously. It is important that you know exactly what we do with your Personal Data.
          </p>
          <p className="text-muted-foreground leading-relaxed font-semibold mt-4">
            How your personal data is used:
          </p>
          <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-4">
            <li>To provide, operate, and maintain our service.</li>
            <li>To notify you regarding any updates or changes to our service.</li>
            <li>Improve, personalize, and expand our service.</li>
            <li>Understand and analyse how you use our service.</li>
            <li>Develop new products, features, and functionality.</li>
            <li>Communicate with you and provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such notifications.</li>
            <li>To detect, prevent and address any technical issues.</li>
            <li>Send you emails for marketing and promotional purposes.</li>
            <li>Find and prevent fraud.</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-3xl font-bold text-foreground pt-8 border-t border-border">LEGAL BASIS FOR PROCESSING PERSONAL DATA UNDER THE GENERAL DATA PROTECTION REGULATION (GDPR)</h2>
          <p className="text-muted-foreground leading-relaxed">
            If you are from the European Economic Area (EEA), TPM HIVE has a legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it.
          </p>
          <p className="text-muted-foreground leading-relaxed">
            TPM HIVE may process your Personal Data because:
          </p>
          <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-4">
            <li>You have explicitly agreed to us processing your Personal Data for a specific reason</li>
            <li>The processing is necessary to perform the agreement we have with you or to take steps to enter into an agreement with you</li>
            <li>The processing is necessary to be in compliance with our Legal Obligations</li>
            <li>The processing is necessary for the purposes of a legitimate interest ("Legitimate Interest") pursued by us, such as:
              <ul className="list-disc list-inside ml-6 mt-2 space-y-1">
                <li>To provide services to you,</li>
                <li>To evaluate, develop or improve our products and services</li>
              </ul>
            </li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-3xl font-bold text-foreground pt-8 border-t border-border">RETENTION OF DATA</h2>
          <p className="text-muted-foreground leading-relaxed">
            TPM HIVE will retain the Personal Data collected from you on our database for as long as it is required for the purposes set out in this Privacy Policy and We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes and enforce our legal agreements and policies. We will only use your Personal Data for those purposes and will make sure that your privacy is fully protected. We shall take reasonable steps to delete or permanently de-identify the Personal Data that is no longer needed.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-3xl font-bold text-foreground pt-8 border-t border-border">TRANSFER OF DATA</h2>
          <p className="text-muted-foreground leading-relaxed">
            Personal Data we hold about you may be transferred to other countries outside your residential country for any of the purposes described in this Privacy Policy.
          </p>
          <p className="text-muted-foreground leading-relaxed">
            You understand and accept that these countries may have differing (and potentially less stringent) laws relating to the degree of confidentiality afforded to the information it holds and that such information can become subject to the laws and disclosure requirements of such countries, including disclosure to administrative bodies, regulatory agencies and private persons, as a result of the applicable administrative or regulatory inquiry. In addition, a number of countries have agreements with other countries providing for the exchange of information for law enforcement, tax and other purposes.
          </p>
          <p className="text-muted-foreground leading-relaxed">
            If we transfer your Personal Data to third parties for purposes stated in this Privacy Policy, we will use best endeavours to put in place appropriate controls and safeguards to ensure that your Personal Data is kept accurate, adequately protected, and processed only for specified and reasonable purposes in a manner that is fair, transparent and has a lawful basis, and is stored for no longer than is absolutely necessary.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-3xl font-bold text-foreground pt-8 border-t border-border">DISCLOSURE OF DATA</h2>
          
          <div className="space-y-4">
            <div>
              <h3 className="text-xl font-semibold text-foreground mb-2">Disclosure for Law Enforcement</h3>
              <p className="text-muted-foreground leading-relaxed">
                Under certain circumstances, TPM HIVE may be required to disclose your Personal Data if required to do so by law or in response to valid requests by administrative authorities (e.g. a sessions court or an administrative agency).
              </p>
            </div>

            <div>
              <h3 className="text-xl font-semibold text-foreground mb-2">Legal Requirements</h3>
              <p className="text-muted-foreground leading-relaxed">
                TPM HIVE may disclose your Personal Data in the good faith belief that such action is necessary to:
              </p>
              <ul className="list-disc list-inside space-y-1 text-muted-foreground ml-4 mt-2">
                <li>To comply with a legal obligation.</li>
                <li>To protect and defend the rights or property of TPM HIVE.</li>
                <li>To prevent or investigate possible wrongdoing in connection with the "Service".</li>
                <li>To protect against legal liability</li>
              </ul>
            </div>

            <div>
              <h3 className="text-xl font-semibold text-foreground mb-2">Security of Data</h3>
              <p className="text-muted-foreground leading-relaxed">
                The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
              </p>
            </div>
          </div>
        </section>

        <section className="space-y-4">
          <h2 className="text-3xl font-bold text-foreground pt-8 border-t border-border">DATA PROTECTION RIGHTS UNDER THE GENERAL DATA PROTECTION REGULATION (GDPR)</h2>
          <p className="text-muted-foreground leading-relaxed">
            If you are a resident of the European Economic Area (EEA), you have certain data protection rights. TPM HIVE aims to take reasonable measures to allow you to correct, amend, delete or limit the use of your Personal Data.
          </p>
          <p className="text-muted-foreground leading-relaxed">
            If you wish to be informed about what Personal Data, we hold about you and if you want it to be removed from our systems, please contact us.
          </p>
          <p className="text-muted-foreground leading-relaxed">
            In certain circumstances, you have the following data protection rights:
          </p>
          <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-4">
            <li><strong className="text-foreground">The right to access, update or delete the information we have on you.</strong> Whenever made possible, you can access, update or request deletion of your Personal Data directly within your account settings section. If you are unable to perform these actions yourself, please contact us to assist you.</li>
            <li><strong className="text-foreground">The right of rectification.</strong> You have the right to have your information rectified if that information is inaccurate or incomplete.</li>
            <li><strong className="text-foreground">The right to object.</strong> You have the right to object to our processing of your Personal Data.</li>
            <li><strong className="text-foreground">The right of restriction.</strong> You have the right to request that we restrict the processing of your personal information.</li>
            <li><strong className="text-foreground">The right to data portability.</strong> You have the right to be provided with a copy of the information we have on you in a structured, machine-readable and commonly used format.</li>
          </ul>
          <p className="text-muted-foreground leading-relaxed mt-4">
            <strong className="text-foreground">Note:</strong> We may ask you to verify your identity in various forms before responding to such requests.
          </p>
          <p className="text-muted-foreground leading-relaxed">
            You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-3xl font-bold text-foreground pt-8 border-t border-border">DATA SECURITY</h2>
          <p className="text-muted-foreground leading-relaxed">
            We are committed to protecting your Personal Data in our custody. We take reasonable steps to ensure appropriate physical, technical and managerial safeguards are in place to protect your Personal Data from unauthorized access, alteration, transmission and deletion. We ensure that the third parties who provide services to us under appropriate contracts, take appropriate security measures to protect your Personal Data in line with our policies.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-3xl font-bold text-foreground pt-8 border-t border-border">LINKS TO OTHER WEBSITES</h2>
          <p className="text-muted-foreground leading-relaxed">
            Our website may contain links to websites of other organisations. This privacy policy does not cover how that organisation processes Personal Data. We encourage you to read the privacy policies on the other websites you visit.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-3xl font-bold text-foreground pt-8 border-t border-border">CHILDREN'S PRIVACY</h2>
          <p className="text-muted-foreground leading-relaxed">
            We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-3xl font-bold text-foreground pt-8 border-t border-border">NOTIFICATION OF CHANGES IN PRIVACY POLICY</h2>
          <p className="text-muted-foreground leading-relaxed">
            We keep our Privacy Policy under regular review to make sure it is up to date and accurate. Any changes we may make to this Privacy Policy in the future will be posted on this page. We recommend that you re-visit this page regularly to check for any updates.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-3xl font-bold text-foreground pt-8 border-t border-border">CONTACT US</h2>
          <p className="text-muted-foreground leading-relaxed">
            For any further queries and complaints related to privacy under applicable laws and regulations, you could reach us at:
          </p>
          <div className="bg-card border border-border rounded-lg p-6 mt-4">
            <p className="text-foreground font-semibold mb-2">THEPEPPERMINT LTD</p>
            <p className="text-muted-foreground">TPM HIVE</p>
            <p className="text-muted-foreground mt-4">E-mail: info@tpmhive.co.uk</p>
            <p className="text-muted-foreground">Contact No: +44 0114 308 8640</p>
          </div>
        </section>
      </div>
    </div>
  )
}

